import { Api } from '@repo/api-definition';
import { Effect } from 'effect';

import './globals.css';
import { FetchHttpClient } from 'effect/unstable/http';
import { HttpApiClient } from 'effect/unstable/httpapi';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import type { ReactNode } from 'react';

const geistSans = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
});
const geistMono = Geist_Mono({
  subsets: ['latin'],
  variable: '--font-geist-mono',
});

const test = Effect.gen(function* test() {
  const client = yield* HttpApiClient.make(Api, {
    baseUrl: 'http://127.0.0.1:8000',
  });
  return yield* client.Greetings.hello();
}).pipe(Effect.provide(FetchHttpClient.layer));

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default async function RootLayout({
  children,
}: LayoutProps<'/'>): Promise<ReactNode> {
  const res = await Effect.runPromise(test);

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children} | {res}
      </body>
    </html>
  );
}
