import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { HttpApiClient } from 'effect/unstable/httpapi';
import { Api } from '@repo/api-definition';
import { Effect } from 'effect';
import { FetchHttpClient } from 'effect/unstable/http';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const test = Effect.gen(function* () {
  const client = yield* HttpApiClient.make(Api, {
    baseUrl: 'http://127.0.0.1:8000',
  });
  return yield* client.Greetings.hello();
}).pipe(Effect.provide(FetchHttpClient.layer));

export default async function RootLayout({ children }: LayoutProps<'/'>) {
  const res = await Effect.runPromise(test);

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children} | {res}
      </body>
    </html>
  );
}
